<?php

/*
Plugin Name: Custom Setting Page
Plugin URI:  http://link to your plugin homepage
Description: Custom Setting Page
*/
	
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class FooterTopSection {
	private $footer_top_section_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'footer_top_section_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'footer_top_section_page_init' ) );
	}

	public function footer_top_section_add_plugin_page() {
		add_menu_page(
			'Footer Top Section', // page_title
			'Custom Setting Page', // menu_title
			'manage_options', // capability
			'custom-footer-page', // menu_slug
			array( $this, 'footer_top_section_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			3 // position
		);
	}

	public function footer_top_section_create_admin_page() {
		$this->footer_top_section_options = get_option( 'footer_top_section_option_name' ); ?>

		<div class="wrap">
			<h2>Footer Top Section</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'footer_top_section_option_group' );
					do_settings_sections( 'footer-top-section-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function footer_top_section_page_init() {
		register_setting(
			'footer_top_section_option_group', // option_group
			'footer_top_section_option_name', // option_name
			array( $this, 'footer_top_section_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'footer_top_section_setting_section', // id
			'Footer Settings', // title
			array( $this, 'footer_top_section_section_info' ), // callback
			'footer-top-section-admin' // page
		);

		add_settings_field(
			'footer_top_title_0', // id
			'Footer Top Title', // title
			array( $this, 'footer_top_title_0_callback' ), // callback
			'footer-top-section-admin', // page
			'footer_top_section_setting_section' // section
		);

		add_settings_field(
			'section_enable_disable_1', // id
			'Section enable/disable', // title
			array( $this, 'section_enable_disable_1_callback' ), // callback
			'footer-top-section-admin', // page
			'footer_top_section_setting_section' // section
		);


		add_settings_section(
			'header_help_title', // id
			'Header Help Title', // title
			array( $this, 'header_top_section_section_info' ), // callback
			'footer-top-section-admin', // page
			'footer_top_section_setting_section' // section
		);
	}

	public function footer_top_section_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['footer_top_title_0'] ) ) {
			$sanitary_values['footer_top_title_0'] = sanitize_text_field( $input['footer_top_title_0'] );
		}

		if ( isset( $input['section_enable_disable_1'] ) ) {
			$sanitary_values['section_enable_disable_1'] = $input['section_enable_disable_1'];
		}


		if ( isset( $input['header_help_title'] ) ) {
			$sanitary_values['header_help_title'] = $input['header_help_title'];
		}


		return $sanitary_values;
	}

	public function footer_top_section_section_info() {
		
	}

	public function footer_top_title_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="footer_top_section_option_name[footer_top_title_0]" id="footer_top_title_0" value="%s">',
			isset( $this->footer_top_section_options['footer_top_title_0'] ) ? esc_attr( $this->footer_top_section_options['footer_top_title_0']) : ''
		);
	}

	public function section_enable_disable_1_callback() {
		printf(
			'<input type="checkbox" name="footer_top_section_option_name[section_enable_disable_1]" id="section_enable_disable_1" value="section_enable_disable_1" %s>',
			( isset( $this->footer_top_section_options['section_enable_disable_1'] ) && $this->footer_top_section_options['section_enable_disable_1'] === 'section_enable_disable_1' ) ? 'checked' : ''
		);
	}


	public function header_top_section_section_info() {
		printf(
			'<input class="regular-text" type="text" name="footer_top_section_option_name[header_help_title]" id="header_help_title" value="%s">',
			isset( $this->footer_top_section_options['header_help_title'] ) ? esc_attr( $this->footer_top_section_options['header_help_title']) : ''
		);
	}

}
if ( is_admin() )
	$footer_top_section = new FooterTopSection();

/* 
 * Retrieve this value with:
 * $footer_top_section_options = get_option( 'footer_top_section_option_name' ); // Array of All Options
 * $footer_top_title_0 = $footer_top_section_options['footer_top_title_0']; // Footer Top Title
 * $section_enable_disable_1 = $footer_top_section_options['section_enable_disable_1']; // Section enable/disable
 */
